// src/App.tsx
import { useState, useEffect, useRef, useCallback } from "react";
import "./App.scss";
import Plyr from "plyr";
import { playlists, Playlist, Video } from "./playlists";
import clsx from "clsx";
import { motion } from "framer-motion";

const useYouTubeSource = false;

const storeNewPlayedPlaylist = (playlist: Playlist) => {
  let playedPlaylists = JSON.parse(
    localStorage.getItem("playedPlaylists") || "[]"
  );
  if (playedPlaylists.includes(`${playlist.title} by ${playlist.dj}`)) {
    return;
  }
  playedPlaylists.push(`${playlist.title} by ${playlist.dj}`);
  localStorage.setItem("playedPlaylists", JSON.stringify(playedPlaylists));
};

const pickRandomPlaylist = (): Playlist => {
  let playedPlaylists = JSON.parse(
    localStorage.getItem("playedPlaylists") || "[]"
  );
  let availablePlaylists = playlists.filter(
    (p) => playedPlaylists.includes(`${p.title}by${p.dj}`) === false
  );
  if (availablePlaylists.length === 0) {
    availablePlaylists = playlists;
  }
  const playlist =
    availablePlaylists[Math.floor(Math.random() * availablePlaylists.length)];
  storeNewPlayedPlaylist(playlist);
  return playlist;
};

const changePlayerSource = (player: Plyr, video: Video) => {
  if (useYouTubeSource) {
    player.source = {
      type: "video",
      sources: [
        {
          src: video.id,
          provider: "youtube",
        },
      ],
    };
  } else {
    player.source = {
      type: "video",
      title: "STAY VIBRANT",
      sources: [
        {
          src: `https://static-jp.qier222.com/stay-vibrant/${video.filename}`,
          size: 1080,
        },
      ],
    };
  }
};

function App() {
  const playerRef = useRef<HTMLVideoElement>(null);
  const [player, setPlayer] = useState<Plyr>();
  const [playlist, setPlaylist] = useState<Playlist>(() => {
    const initial = pickRandomPlaylist();
    return initial;
  });
  const [video, setVideo] = useState<Video>(playlist.videos[0]);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [isStarted, setIsStarted] = useState<boolean>(false);
  const [showMenu, setShowMenu] = useState<boolean>(false);
  const [showBigTitle, setShowBigTitle] = useState<boolean>(
    document.body.clientWidth > 768 ? true : false
  );
  const [hover, setHover] =
    useState<"none" | "bigPlay" | "bigTitle" | "title">("none");

  const changePlaylist = useCallback(
    (playlist: Playlist, source: "pickRandomPlaylist" | "" = "") => {
      setPlaylist(playlist);
      setVideo(playlist.videos[0]);
      setShowMenu(false);
      if (source !== "pickRandomPlaylist") {
        storeNewPlayedPlaylist(playlist);
      }
    },
    []
  );

  const nextVideoOrPlaylist = useCallback(() => {
    if (playlist.videos.length === 1) {
      changePlaylist(pickRandomPlaylist(), "pickRandomPlaylist");
    } else {
      const currentVideoIndex = playlist.videos.findIndex(
        (v) => v.id === video.id
      );
      if (currentVideoIndex + 1 === playlist.videos.length) {
        changePlaylist(pickRandomPlaylist(), "pickRandomPlaylist");
        return;
      }
      setVideo(playlist.videos[currentVideoIndex + 1]);
    }
  }, [changePlaylist, playlist, video]);

  useEffect(() => {
    if (!playerRef.current) return;
    setPlayer(
      new Plyr(playerRef.current, {
        controls: [],
        youtube: {
          start: 1,
        },
      })
    );
  }, []);

  useEffect(() => {
    if (!player) return;
    changePlayerSource(player, video);
    if (isStarted) {
      const ready = () => player.play();
      player.once("ready", ready);
    }
  }, [player, video, playlist, isStarted]);

  useEffect(() => {
    if (!player) return;
    const pause = () => setIsPlaying(false);
    const play = () => setIsPlaying(true);
    const ended = () => nextVideoOrPlaylist();
    player.on("pause", pause);
    player.on("play", play);
    player.on("ended", ended);
    return () => {
      player.off("pause", pause);
      player.off("play", play);
      player.off("ended", ended);
    };
  }, [player, nextVideoOrPlaylist]);

  const isShowGreyLayer =
    video.showGreyLayer !== undefined
      ? video.showGreyLayer
      : playlist.showGreyLayer !== undefined
      ? playlist.showGreyLayer
      : true;
  const specialBigTitle =
    video.specialBigTitle !== undefined
      ? video.specialBigTitle
      : playlist.specialBigTitle !== undefined
      ? playlist.specialBigTitle
      : "STAY VIBRANT";

  return (
    <div className="App">
      <div className="video-wrapper">
        <video ref={playerRef}></video>
      </div>

      <div
        className={clsx("grey-layer", !isShowGreyLayer && "display-none")}
      ></div>

      <div
        className={clsx(
          "big-play-button glitch-animation",
          isStarted && "display-none"
        )}
      >
        <motion.span
          onClick={() => {
            player?.play();
            setIsStarted(true);
            setIsPlaying(true);
          }}
          data-name="PLAY"
          className={clsx(hover === "bigPlay" && "glitch-container")}
          onMouseEnter={() => {
            setHover("bigPlay");
          }}
          onMouseLeave={() => {
            setHover("none");
          }}
          initial={{ scale: 10 }}
          animate={{ scale: 1 }}
          transition={{ type: "spring", duration: 0.5, bounce: 0.25 }}
          exit={{ opacity: 0 }}
        >
          <span>PLAY</span>
        </motion.span>
      </div>

      <div
        className={clsx(
          "big-title  glitch-animation",
          (!isStarted || !showBigTitle) && "display-none"
        )}
        onClick={() => setShowMenu(false)}
      >
        <span
          onClick={() => setShowBigTitle(false)}
          data-name={specialBigTitle}
          className={clsx(hover === "bigTitle" && "glitch-container")}
          onMouseEnter={() => {
            setHover("bigTitle");
          }}
          onMouseLeave={() => {
            setHover("none");
          }}
        >
          <span>{specialBigTitle}</span>
        </span>
      </div>

      <div
        className={clsx("info", (!isStarted || showBigTitle) && "display-none")}
        onClick={() => setShowMenu(false)}
      >
        <div className="top">
          <div
            className="website-title  glitch-animation"
            onClick={() => setShowBigTitle(true)}
            onMouseEnter={() => {
              setHover("title");
            }}
            onMouseLeave={() => {
              setHover("none");
            }}
          >
            <span
              data-name={specialBigTitle}
              className={clsx(hover === "title" && "glitch-container")}
            >
              {specialBigTitle}
            </span>
          </div>
          <div className="playlist-details">
            <a
              href={`https://www.youtube.com/watch?v=${video.id}`}
              className="title"
            >
              {playlist.title}
            </a>
            <div className="dj">{playlist.dj}</div>
          </div>
          <a className="credit" href="https://github.com/qier222/stay-vibrant">
            COLLECTED BY QIER222
          </a>
        </div>
        <div className="bottom">
          <div className="playlist-details">
            <a
              href={`https://www.youtube.com/watch?v=${video.id}`}
              className="title"
            >
              {playlist.title}
            </a>
            <div className="dj">{playlist.dj}</div>
          </div>
          <div className="controls">
            <div
              className="pause"
              onClick={() => {
                player?.togglePlay();
                setIsPlaying(!isPlaying);
              }}
            >
              {isPlaying ? "PAUSE" : "PLAY"}
            </div>
            <div
              className="menu"
              onClick={(e) => {
                e.stopPropagation();
                setShowMenu(true);
              }}
            >
              MENU
            </div>
          </div>
        </div>
      </div>
      <div className={clsx("menu-panel", showMenu && "show")}>
        <div className="playlists">
          {playlists.map((p) => (
            <div
              className="playlist"
              onClick={() => changePlaylist(p)}
              key={`${p.title}by${p.dj}`}
            >
              <div className="title">
                {playlist.title === p.title && playlist.dj === p.dj && "🔊 "}
                {p.title}
              </div>
              <div className="dj">{p.dj}</div>
            </div>
          ))}
        </div>
        <div className="buttons">
          <div
            className="next"
            onClick={() =>
              changePlaylist(pickRandomPlaylist(), "pickRandomPlaylist")
            }
          >
            <span>NEXT</span>
          </div>
          <div className="close" onClick={() => setShowMenu(false)}>
            <span>CLOSE</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <div class="video-wrapper">
      <video ref="videoPlayer" class="plyr"></video>
    </div>
    <div class="grey" v-show="true"></div>
    <div class="stay-vibrant" v-show="!showInfo && clickPlay && !isMobile">
      <span @click="doShowInfo">STAY VIBRANT</span>
    </div>
    <div class="info" v-show="showInfo || isMobile">
      <div class="top">
        <div class="title">STAY VIBRANT</div>
        <div class="video-info">
          <div class="title link" @click="toYouTube">
            {{ playlist.title }}
          </div>
          <div class="subtitle">
            {{ playlist.subtitle }}
          </div>
        </div>
        <div class="menu">
          <div class="link" @click="toQier222">COLLECTED BY QIER222</div>
        </div>
      </div>
      <div class="bottom">
        <div>
          <div class="title link" @click="toYouTube">
            {{ playlist.title }}
          </div>
          <div class="subtitle">
            {{ playlist.subtitle }}
          </div>
        </div>
        <div class="controls">
          <div class="play" @click="playOrPause">
            {{ playButtonText }}
          </div>
          <div class="next" @click="nextPlaylist">
            NEXT
          </div>
        </div>
      </div>
    </div>
    <div class="play-button-layout" v-if="showStartButton">
      <div
        :class="{ 'play-animation': clickPlay }"
        class="play-button"
        @click="startPlay"
      >
        PLAY
      </div>
    </div>
  </div>
</template>

<script>
import "@/assets/css/plyr.css";
import Plyr from "plyr";
import playlists from "./playlists";

export default {
  name: "App",
  data() {
    return {
      player: null,
      showInfo: false,
      playlist: null,
      playingVideoID: null,
      timer: null,
      clickPlay: false,
      showStartButton: true,
      playButtonText: "PLAY",
    };
  },
  computed: {
    windowWidth() {
      return document.body.clientWidth;
    },
    isMobile() {
      return this.windowWidth <= 768;
    },
  },
  created() {
    let playedPlaylists = JSON.parse(localStorage.getItem("playedPlaylists"));
    if (playedPlaylists === null) {
      playedPlaylists = [];
      localStorage.setItem("playedPlaylists", JSON.stringify([]));
    }
    this.playlist = this.pickAUnplayedPlaylist();
    if (playedPlaylists.includes(this.playlist.title) === false) {
      playedPlaylists.push(this.playlist.title);
      localStorage.setItem("playedPlaylists", JSON.stringify(playedPlaylists));
    }
  },
  mounted() {
    this.player = new Plyr(this.$refs.videoPlayer, {
      controls: [],
      youtube: {},
    });
    this.nextVideo();
    this.player.on("ended", () => {
      this.nextVideo();
    });
    this.player.on("pause", () => {
      this.playButtonText = "PLAY";
    });
    this.player.on("playing", () => {
      this.playButtonText = "PAUSE";
    });
  },
  methods: {
    startPlay() {
      this.clickPlay = true;
      this.player.play();
      this.player.autoplay = true;
      setTimeout(() => {
        this.showStartButton = false;
      }, 300);
    },
    playOrPause() {
      this.player.togglePlay();
    },
    doShowInfo() {
      this.showInfo = true;
      this.setShowInfoTimer();
    },
    setShowInfoTimer() {
      if (this.timer !== null) {
        clearTimeout(this.timer);
      }
      if (this.windowWidth > 768) {
        this.timer = setTimeout(() => {
          this.showInfo = false;
        }, 15000);
      }
    },
    pickAUnplayedPlaylist() {
      let playedPlaylists = JSON.parse(localStorage.getItem("playedPlaylists"));
      let availablePlaylists = playlists.filter((p) => {
        if (
          playedPlaylists.includes(p.title) === false &&
          p.title !== this.playlist?.title
        )
          return p;
      });
      if (availablePlaylists.length !== 0) {
        return availablePlaylists[
          Math.floor(Math.random() * availablePlaylists.length)
        ];
      } else {
        localStorage.setItem("playedPlaylists", JSON.stringify([]));
        return this.pickAUnplayedPlaylist();
      }
    },
    nextVideo() {
      this.playButtonText = "PLAY";
      this.setShowInfoTimer();
      let videoID = null;
      if (this.playingVideoID === null) {
        videoID = this.playlist.videos[0];
      } else {
        let currentIndex = this.playlist.videos.indexOf(this.playingVideoID);
        videoID = this.playlist.videos[currentIndex + 1];
        if (videoID === undefined) {
          this.nextPlaylist();
          return;
        }
      }
      this.playingVideoID = videoID;
      this.player.source = {
        type: "video",
        sources: [
          {
            src: videoID,
            provider: "youtube",
          },
        ],
      };
    },
    nextPlaylist() {
      this.playlist = this.pickAUnplayedPlaylist();
      this.playingVideoID = null;
      this.nextVideo();
    },
    toYouTube() {
      window.open(`https://www.youtube.com/watch/${this.playingVideoID}`);
    },
    toQier222() {
      window.open("https://github.com/qier222");
    },
  },
};
</script>

<style lang="scss">
@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap");

body {
  margin: 0;
  font-weight: 600;
  font-family: Inter, sans-serif;
}

.video-wrapper {
  width: 100vw;
  height: 100vh;
  overflow: hidden;
}

.plyr {
  height: 100vh;
  z-index: 1;
}

.grey {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  height: 100vh;
  width: 100vw;
  background: rgba(0, 0, 0, 0.4);
  backdrop-filter: saturate(160%) contrast(110%) brightness(104%);
  z-index: 1;
}

.plyr__video-embed iframe {
  top: -50%;
  height: 200%;
}

.stay-vibrant {
  color: #fff;
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  height: 100vh;
  width: 100vw;
  mix-blend-mode: difference;
  z-index: 2;

  display: flex;
  justify-content: center;
  align-items: center;

  font-size: 8rem;
  font-weight: 700;

  span {
    cursor: pointer;
  }
}

.info {
  color: #fff;
  position: fixed;
  top: 0px;
  right: 0;
  bottom: 0;
  left: 0;
  height: 100vh;
  width: 100vw;
  mix-blend-mode: difference;
  z-index: 2;
  font-size: 18px;

  .link:hover {
    text-decoration: underline;
    cursor: pointer;
  }

  .top {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 17px 32px 0 32px;
    .title {
      font-size: 64px;
      font-weight: 700;
    }
    .menu div {
      margin-right: 18px;
    }
    .video-info {
      display: none;
    }
  }

  .bottom {
    position: fixed;
    left: 0;
    right: 0;
    bottom: 0;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    padding: 0 32px 32px 32px;

    .title {
      font-weight: 700;
      font-size: 24px;
      margin-bottom: 8px;
      margin-left: 4px;
    }
    .subtitle {
      font-size: 18px;
      font-weight: 600;
      margin-left: 4px;
    }
    .controls {
      display: flex;
      align-items: center;
      font-size: 24px;
      cursor: pointer;
      user-select: none;
      .play {
        margin-right: 48px;
        transition: all 0.4s;
        &:hover {
          letter-spacing: 2px;
        }
      }
      .next {
        margin-right: 24px;
        transition: all 0.4s;
        &:hover {
          letter-spacing: 2px;
        }
      }
    }
  }
}

.play-button-layout {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  height: 100vh;
  width: 100vw;
  z-index: 200;

  display: flex;
  justify-content: center;
  align-items: center;

  @keyframes zooms {
    0% {
      height: 360px;
      width: 360px;
    }
    100% {
      height: 100vh;
      width: 100vw;
    }
  }

  .play-button {
    height: 320px;
    width: 320px;
    box-shadow: 0 0 0 4069px rgba(0, 0, 0, 0.98);
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;

    font-size: 64px;
    color: #fff;
    backdrop-filter: blur(12px);

    transition: all 0.6s;

    &:hover {
      letter-spacing: 4px;
      height: 360px;
      width: 360px;
    }
  }

  .play-animation {
    cursor: default;
    animation-duration: 0.3s;
    animation-timing-function: cubic-bezier(0.5, 0, 0.75, 0);
    animation-name: zooms;
    animation-fill-mode: forwards;
    backdrop-filter: none;
    color: rgba(255, 255, 255, 0);
  }
}

@media (max-width: 768px) {
  .plyr {
    width: calc(100vh / 9 * 16);
    margin-left: calc((100vh / 9 * 16 - 100vw) / -2);
    max-width: unset;
  }

  .stay-vibrant {
    font-size: 4rem;
    text-align: center;
  }

  .info {
    .top {
      flex-direction: column;
      align-items: flex-start;
      .title {
        font-size: 3rem;
      }
      .menu {
        margin-top: 6px;
        font-size: 0.6rem;
        opacity: 0.28;
      }
      .video-info {
        margin-top: -4px;
        display: block;
        .title {
          font-size: 2.2rem;
        }
        .subtitle {
          margin-top: 3px;
          font-size: 1.4rem;
        }
      }
    }
    .bottom {
      flex-direction: column;
      .title {
        font-size: 1.4rem;
        display: none;
      }
      .subtitle {
        font-size: 1rem;
        display: none;
      }
      .controls {
        margin-bottom: 24px;
        font-size: 1.2rem;
        justify-content: flex-start;
        text-align: center;
        width: 100%;
        .play {
          margin-right: 0;
          flex: 1;
        }
        .next {
          flex: 1;
          margin-right: 0;
        }
      }
    }
  }
}

@media (max-width: 414px) {
  .info .top {
    .title {
      font-size: 2.9rem;
    }
    .menu {
      font-size: 0.6rem;
    }
    .video-info {
      .title {
        font-size: 2.2rem;
      }
      .subtitle {
        font-size: 1.4rem;
      }
    }
  }
}

@media (max-width: 375px) {
  .info .top {
    .title {
      font-size: 2.6rem;
    }
    .menu {
      font-size: 0.6rem;
    }
    .video-info {
      .title {
        font-size: 1.8rem;
      }
      .subtitle {
        font-size: 1.3rem;
      }
    }
  }
}
@media (max-width: 360px) {
  .info .top .title {
    font-size: 2.1rem;
  }
}
</style>
